#!/bin/sh

API_KEY=PXtkZWwp8oGdvBgfH0TE
PROJ_NAME=$(basename `pwd`)

/usr/bin/wget -q -O /dev/null http://localhost/redmine/sys/fetch_changesets?key=${API_KEY}
cd /var/www/html/${PROJ_NAME} && git --git-dir=.git pull

